### ISSUE TITLE
Class names (singular/plural)

### ISSUE THREAD

**Issue by mnapoli** [rossriley/php-scalar-objects#7]
Current class names:
- Arrays
- Float
- Integer
- Nulls
- Number
- String

This is inconsistent, some are singular, some plurals.

I suggest the following naming:
- Array
- Float
- Integer
- Null
- Number
- String

**Comment by rossriley** [comment]
Hey. This is purely due to protected keywords. See: https://github.com/rossriley/php-scalar-objects/issues/1

**Comment by mnapoli** [comment]
Damn, I forgot about that. Would suffixing the names with something like `ArrayHandler`, or `ArrayClass` be a solution? At least it would be consistent, `Arrays` really makes no sense because it can be interpreted as "array of array".

**Comment by rossriley** [comment]
Yes, I agree. It's not crucial since when we make an RFC for this the classes will be implemented as native zend_class types just like the Spl... classes so I imagine we'll rename them something like ScalarStringHandler unless PHP core is going to implement namespaces for internal classes (which I doubt will happen).

However it'll be good to make the code sane in this project in the meantime, it will give us less hassle when we get it to RFC stage too.

**Comment by rossriley** [comment]
Fixed with: https://github.com/rossriley/php-scalar-objects/commit/260b2b3c15e29b7156fc40ee59ff618f606414d8
